"""Regenerate EVERY document figure from committed scripts + data.

Runs every generator in this directory (each is self-contained and reads only
saved, committed data), then verifies that every figure referenced by the
report exists and was refreshed. This is the regenerability gate for
document/fig/transport_sweeps -- see document/PLOTS.md.

Run:  OMP_NUM_THREADS=1 python phonon/scripts/figures/make_all.py
"""
from __future__ import annotations

import re
import subprocess
import sys
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
FIGDIR = ROOT / "document/fig/transport_sweeps"
SRC = ROOT / "document/src"
SKIP = {"make_all.py"}


def referenced_figures():
    """(subdir, stem) pairs for every figure the report includes.

    Covers all figure subdirs under document/fig, not only
    transport_sweeps -- the toy_grid/gband/newton figures were
    previously outside the gate and went stale silently.
    """
    pairs = set()
    pat = re.compile(r"(transport_sweeps|toy_grid|gband|newton)/"
                     r"([A-Za-z0-9_]+)\.pdf")
    for tex in list(SRC.rglob("*.tex")) + [ROOT / "document/report.tex"]:
        pairs.update(pat.findall(tex.read_text(errors="ignore")))
    return sorted(pairs)


def main():
    t0 = time.time()
    # underscore scripts are extractors: they read uncommitted run
    # artifacts (cluster/, studies/out) to refresh the committed
    # distillates in phonon/scripts/data and cannot run everywhere
    scripts = sorted(p for p in HERE.glob("*.py")
                     if p.name not in SKIP and not p.name.startswith("_"))
    failures = []
    for s in scripts:
        r = subprocess.run([sys.executable, str(s)], capture_output=True,
                           text=True, cwd=str(ROOT))
        status = "ok" if r.returncode == 0 else f"FAIL rc={r.returncode}"
        print(f"  {s.name:40s} {status}")
        if r.returncode != 0:
            failures.append((s.name, (r.stderr or r.stdout).strip()[-800:]))

    refs = [(d, s) for d, s in referenced_figures()]
    paths = {(d, s): ROOT / "document/fig" / d / f"{s}.pdf" for d, s in refs}
    missing = [f"{d}/{s}" for (d, s), p in paths.items() if not p.exists()]
    stale = [f"{d}/{s}" for (d, s), p in paths.items()
             if p.exists() and p.stat().st_mtime < t0 - 1]

    print(f"\nreferenced figures: {len(refs)}; regenerated this run: "
          f"{len(refs) - len(missing) - len(stale)}")
    if stale:
        print("NOT regenerated by any script here (see PLOTS.md for their "
              "generators):")
        for f in stale:
            print(f"  - {f}")
    if missing:
        print("MISSING figures:")
        for f in missing:
            print(f"  - {f}")
    for name, err in failures:
        print(f"\n=== {name} FAILED ===\n{err}")
    return 1 if (failures or missing) else 0


if __name__ == "__main__":
    raise SystemExit(main())
