"""Conservation gate (V2) for the surgical rank subtraction
(phonon/docs/ir_residue_derivation.md Sec. 4).

Bed: 1D diatomic chain, 3-cell device (6 DOF), semi-infinite leads via
the production spectral NEVP OBC at eta = 0, T_L != T_R. The
translation subspace is rank 1; the vertex is a random S3-symmetric
tensor WITHOUT the acoustic sum rule (the device-truncation leak is
the generic case). Negative-axis legs are generated by the bosonic
fold, so the fold is exact by construction and the derived balance
statements can be tested at machine precision:

  (1) bare triangle identity:
        B = sum_w w Tr[Sigma^< G^> - Sigma^> G^<] = 0
  (2) subtracted identity, Gbar-paired:
        sum_w w Tr[Sigma_sub^< Gbar^> - Sigma_sub^> Gbar^<] = 0
  (3) the G-paired ledger defect Delta (the CM-drag term) -- reported,
      not gated
  (4) detailed balance of Sigma_sub at T_L = T_R
  (5) the disease and the cure: |Sigma(w_out)| under a dw ladder --
      bare grows ~1/dw, sub converges

Run:  QTX_ARRAY_MODULE=numpy OMP_NUM_THREADS=1 \
        python phonon/studies/_ir_conserve_gate.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[2]
for p in (str(ROOT), str(ROOT / "src")):
    if p not in sys.path:
        sys.path.insert(0, p)

from quatrex.phonon.ir_subtraction import bose, bose_pole_coeff  # noqa: E402

ND = 2          # DOF per cell (diatomic 1D chain)
NSLAB = 3
N = ND * NSLAB
K_SPRING = 6.0  # THz^2 scale
M1, M2 = 1.0, 2.4
T_L, T_R = 305.0, 295.0
W_MAX = 6.0


def chain_blocks():
    s11, s22 = 2 * K_SPRING / M1, 2 * K_SPRING / M2
    s12 = -K_SPRING / np.sqrt(M1 * M2)
    d00 = np.array([[s11, s12], [s12, s22]], complex)
    d01 = np.array([[0.0, 0.0], [s12, 0.0]], complex)
    return d00, d01, d01.conj().T


_SPECTRAL = None


def spectral():
    global _SPECTRAL
    if _SPECTRAL is None:
        from qttools.boundary_conditions.obc import Spectral
        from qttools.nevp import Full
        _SPECTRAL = Spectral(nevp=Full(), block_sections=1)
    return _SPECTRAL


def contact_sigmas(ws, d00, d01, d10):
    obc = spectral()
    z2 = (ws * ws + 0j).astype(complex)
    eye = np.eye(ND)
    m_00 = z2[:, None, None] * eye - d00[None]
    m_01 = np.broadcast_to(-d01, m_00.shape).copy()
    m_10 = np.broadcast_to(-d10, m_00.shape).copy()
    g_00 = obc(m_00, m_01, m_10, "left")
    sig_l = m_10 @ g_00 @ m_01
    flip = lambda a: np.flip(a, axis=(-2, -1))
    g_nn = obc(flip(m_00), flip(m_10), flip(m_01), "right")
    sig_r = m_01 @ flip(g_nn) @ m_10
    return sig_l, sig_r


def dense_g(ws, d00, d01, d10, t_l, t_r):
    sig_l, sig_r = contact_sigmas(ws, d00, d01, d10)
    dev = np.zeros((N, N), complex)
    for i in range(NSLAB):
        dev[i * ND:(i + 1) * ND, i * ND:(i + 1) * ND] = d00
        if i + 1 < NSLAB:
            dev[i * ND:(i + 1) * ND, (i + 1) * ND:(i + 2) * ND] = d01
            dev[(i + 1) * ND:(i + 2) * ND, i * ND:(i + 1) * ND] = d10
    gl, gg = [], []
    for i, w in enumerate(ws):
        sys_m = (w * w) * np.eye(N) - dev
        sys_m[:ND, :ND] -= sig_l[i]
        sys_m[-ND:, -ND:] -= sig_r[i]
        gr = np.linalg.solve(sys_m, np.eye(N))
        ga = gr.conj().T
        gam_l = np.zeros((N, N), complex)
        gam_r = np.zeros((N, N), complex)
        gam_l[:ND, :ND] = 1j * (sig_l[i] - sig_l[i].conj().T)
        gam_r[-ND:, -ND:] = 1j * (sig_r[i] - sig_r[i].conj().T)
        n_l, n_r = bose(w, t_l), bose(w, t_r)
        gl.append(gr @ (1j * (n_l * gam_l + n_r * gam_r)) @ ga)
        gg.append(gr @ (1j * ((n_l + 1) * gam_l + (n_r + 1) * gam_r)) @ ga)
    return np.array(gl), np.array(gg)


def cm_channel(d00, d01, d10):
    """(v_L, v_R, P) of the centre-of-mass channel (rank 1 here).

    The subtracted field is the EXACT damped-free-particle (CM) pair

        S^R(w)     = P / (w^2 + i w v_T),        v_T = v_L + v_R,
        S^{<,>}(w) = S^R [ i sum_a 2 w n_a^{<,>}(w) v_a ] S^A  x  P

    (n^< = n_a, n^> = n_a + 1): fold- and KMS-exact by construction,
    singular Laurent parts C2/w^2 -+ V^-1/w identical to the series
    form."""
    t = np.zeros(N)
    sqm = np.sqrt([M1, M2])
    for s in range(NSLAB):
        t[s * ND:(s + 1) * ND] = sqm
    t /= np.linalg.norm(t)
    ladder = np.array([2e-3, 4e-3, 8e-3, 1.6e-2])
    v = {"L": [], "R": []}
    for w in ladder:
        sig_l, sig_r = contact_sigmas(np.array([w]), d00, d01, d10)
        for name, sig, sl in (("L", sig_l[0], slice(0, ND)),
                              ("R", sig_r[0], slice(N - ND, N))):
            gam = np.zeros((N, N), complex)
            gam[sl, sl] = 1j * (sig - sig.conj().T)
            v[name].append(t @ gam.real @ t / (2 * w))
    v0 = {}
    for name in ("L", "R"):
        coef = np.polynomial.polynomial.polyfit(
            ladder ** 2, np.array(v[name]), 1)
        v0[name] = coef[0]
    return v0["L"], v0["R"], np.outer(t, t)


def s_pair(w, v_l, v_r, P, t_l, t_r):
    """Exact CM-channel (S^<, S^>) at frequency w != 0."""
    v_t = v_l + v_r
    sr = 1.0 / (w * w + 1j * w * v_t)
    drive_l = 2.0 * w * (bose(w, t_l) * v_l)
    drive_g = 2.0 * w * ((bose(w, t_l) + 1.0) * v_l)
    drive_l += 2.0 * w * (bose(w, t_r) * v_r)
    drive_g += 2.0 * w * ((bose(w, t_r) + 1.0) * v_r)
    return (1j * sr * drive_l * np.conj(sr)) * P, \
           (1j * sr * drive_g * np.conj(sr)) * P


def s3_vertex(seed=7):
    rng = np.random.default_rng(seed)
    phi = rng.normal(size=(N, N, N))
    sym = np.zeros_like(phi)
    from itertools import permutations
    for p in permutations((0, 1, 2)):
        sym += np.transpose(phi, p)
    return sym / 6.0


def ring(phi, fa, fb):
    t1 = np.einsum("ace,cb->aeb", phi, fa)
    t2 = np.einsum("aeb,ed->abd", t1, fb)
    return np.einsum("abd,jdb->aj", t2, phi)


def bubble(phi, legs_l, legs_g, npos, dw):
    """Sigma^{<,>}(k) for all bins k in [-npos, npos] (index offset npos)."""
    nax = 2 * npos + 1
    sig_l = np.zeros((nax, N, N), complex)
    sig_g = np.zeros((nax, N, N), complex)
    for m in range(-npos, npos + 1):
        acc_l = np.zeros((N, N), complex)
        acc_g = np.zeros((N, N), complex)
        for k in range(max(-npos, m - npos), min(npos, m + npos) + 1):
            acc_l += ring(phi, legs_l[k + npos], legs_l[m - k + npos])
            acc_g += ring(phi, legs_g[k + npos], legs_g[m - k + npos])
        sig_l[m + npos] = acc_l * dw
        sig_g[m + npos] = acc_g * dw
    return sig_l, sig_g


def balance(ws_full, sig_l, sig_g, pair_l, pair_g):
    num = 0.0 + 0j
    den = 0.0
    for i, w in enumerate(ws_full):
        a = np.trace(sig_l[i] @ pair_g[i])
        b = np.trace(sig_g[i] @ pair_l[i])
        num += w * (a - b)
        den += abs(w) * (abs(a) + abs(b))
    return abs(num) / max(den, 1e-300)


def make_legs(dw, npos, d00, d01, d10, t_l, t_r, v_l, v_r, P):
    ws_pos = np.arange(1, npos + 1) * dw
    gl_p, gg_p = dense_g(ws_pos, d00, d01, d10, t_l, t_r)
    nax = 2 * npos + 1
    legs_l = np.zeros((nax, N, N), complex)
    legs_g = np.zeros((nax, N, N), complex)
    for i in range(npos):
        legs_l[npos + 1 + i] = gl_p[i]
        legs_g[npos + 1 + i] = gg_p[i]
        legs_l[npos - 1 - i] = gg_p[i].T      # bosonic fold
        legs_g[npos - 1 - i] = gl_p[i].T
    s_l = np.zeros_like(legs_l)
    s_g = np.zeros_like(legs_g)
    for k in range(-npos, npos + 1):
        if k == 0:
            continue
        s_l[k + npos], s_g[k + npos] = s_pair(k * dw, v_l, v_r, P, t_l, t_r)
    return legs_l, legs_g, s_l, s_g


def main():
    d00, d01, d10 = chain_blocks()
    t = np.zeros(N)
    t[0::2], t[1::2] = np.sqrt(M1), np.sqrt(M2)
    t /= np.linalg.norm(t)
    asr = np.linalg.norm((d00 + d01 + d10) @ t[:ND] * np.linalg.norm(t))
    print(f"chain fc2 ASR: |(D00+D01+D10) t| = {asr:.2e}")

    v_l, v_r, P = cm_channel(d00, d01, d10)
    c2 = (2 * bose_pole_coeff(T_L) * v_l
          + 2 * bose_pole_coeff(T_R) * v_r) / (v_l + v_r) ** 2
    print(f"channel: v_L={v_l:.4f} v_R={v_r:.4f} THz, C2 amp {c2:.4f}")
    phi = s3_vertex()

    report = {}
    print(f"\n{'dw':>8} {'B_bare':>10} {'B_sub(Gbar)':>12} {'Delta(G)':>10} "
          f"{'|S^<(dw)|/|G^<(dw)|':>20}")
    for dw in (0.1, 0.05, 0.025):
        npos = int(round(W_MAX / dw))
        legs_l, legs_g, s_l, s_g = make_legs(
            dw, npos, d00, d01, d10, T_L, T_R, v_l, v_r, P)
        ws_full = np.arange(-npos, npos + 1) * dw
        bl, bg = bubble(phi, legs_l, legs_g, npos, dw)
        b_bare = balance(ws_full, bl, bg, legs_l, legs_g)
        gbar_l, gbar_g = legs_l - s_l, legs_g - s_g
        sl_sub, sg_sub = bubble(phi, gbar_l, gbar_g, npos, dw)
        b_sub = balance(ws_full, sl_sub, sg_sub, gbar_l, gbar_g)
        # G-paired defect of the subtracted bubble
        num = sum(ws_full[i] * (np.trace(sl_sub[i] @ legs_g[i])
                                - np.trace(sg_sub[i] @ legs_l[i]))
                  for i in range(len(ws_full)))
        den = sum(abs(ws_full[i]) * (abs(np.trace(sl_sub[i] @ legs_g[i]))
                                     + abs(np.trace(sg_sub[i] @ legs_l[i])))
                  for i in range(len(ws_full)))
        delta = abs(num) / max(den, 1e-300)
        frac = np.linalg.norm(s_l[npos + 1]) / np.linalg.norm(legs_l[npos + 1])
        print(f"{dw:8.3f} {b_bare:10.2e} {b_sub:12.2e} {delta:10.2e} "
              f"{frac:20.3f}")
        report[dw] = {"b_bare": b_bare, "b_sub": b_sub, "delta": delta}

        # disease/cure on this bed: output-bin norm at w_out = 1.0
        m = int(round(1.0 / dw)) + npos
        report[dw]["sig_bare_1thz"] = float(np.linalg.norm(bl[m]))
        report[dw]["sig_sub_1thz"] = float(np.linalg.norm(sl_sub[m]))

    print("\n|Sigma^<(1 THz)| ladder (disease vs cure):")
    for dw in (0.1, 0.05, 0.025):
        print(f"  dw={dw:6.3f}  bare {report[dw]['sig_bare_1thz']:.4e}  "
              f"sub {report[dw]['sig_sub_1thz']:.4e}")

    # (4) detailed balance at equilibrium
    dw, npos = 0.05, int(round(W_MAX / 0.05))
    legs_l, legs_g, s_l, s_g = make_legs(
        dw, npos, d00, d01, d10, 300.0, 300.0, v_l, v_r, P)
    sl_sub, sg_sub = bubble(phi, legs_l - s_l, legs_g - s_g, npos, dw)
    ws_pos = np.arange(1, npos + 1) * dw
    ratio = []
    for i, w in enumerate(ws_pos):
        n = bose(w, 300.0)
        det = np.linalg.norm(sg_sub[npos + 1 + i] * n
                             - sl_sub[npos + 1 + i] * (n + 1.0))
        nrm = np.linalg.norm(sg_sub[npos + 1 + i] * n) + 1e-300
        ratio.append(det / nrm)
    print(f"\ndetailed balance of Sigma_sub at equilibrium "
          f"(max rel residual over w): {max(ratio):.2e}")

    outdir = ROOT / "phonon/studies/out/ir_residue"
    outdir.mkdir(parents=True, exist_ok=True)
    (outdir / "conserve_gate.json").write_text(
        json.dumps({str(k): v for k, v in report.items()}, indent=1))
    print(f"wrote {outdir / 'conserve_gate.json'}")


if __name__ == "__main__":
    main()
