"""2H-MoS2 bulk FC campaign driver (cross-plane kappa_z vs Sood 2019).
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "phonon"))

CFG_DIR = REPO / "phonon/configs/mos2"

#: Config triples, keyed by exchange-correlation variant. The relax stage runs
#: at dense k on the 6-atom cell and its relaxed structure is injected into the
#: statics config; only ``vasp.incar_extra`` differs between variants, so a
#: variant pair is a controlled test of the functional.
VARIANTS = {
    "d3": ("mos2_relax_vasp.yaml", "mos2_bulk_vasp.yaml",
           "mos2_bulk_vasp.gen.yaml"),
    "vdwdfcx": ("mos2_relax_vdwdfcx.yaml", "mos2_bulk_vdwdfcx.yaml",
                "mos2_bulk_vdwdfcx.gen.yaml"),
}


def validate_relaxed(cell, ref_cell) -> None:
    """Geometry gates: symmetry, bonds, interlayer gap, fixed cell."""
    import spglib

    if not np.allclose(cell.cell, ref_cell.cell, atol=1e-6):
        raise RuntimeError("cell changed during ISIF=2 relax -- inspect")

    lat = np.asarray(cell.cell)
    frac = cell.scaled_positions
    nums = [42 if s == "Mo" else 16 for s in cell.symbols]
    sg = spglib.get_spacegroup((lat, frac, nums), symprec=1e-4)
    print(f"[relax] spacegroup: {sg}", flush=True)
    if "194" not in sg:
        raise RuntimeError(f"symmetry broke during relax: {sg}")

    cart = frac @ lat
    imgs = np.array([[i, j, k] for i in (-1, 0, 1) for j in (-1, 0, 1)
                     for k in (-1, 0, 1)])

    def dmin(i, j):
        return min(np.linalg.norm(cart[i] - cart[j] + n @ lat) for n in imgs)

    mo = [i for i, s in enumerate(cell.symbols) if s == "Mo"]
    ss = [i for i, s in enumerate(cell.symbols) if s == "S"]
    bonds = sorted(dmin(mo[0], j) for j in ss)[:2]
    print(f"[relax] Mo-S bond: {bonds[0]:.4f} A", flush=True)
    if not (2.30 < bonds[0] < 2.55):
        raise RuntimeError(f"Mo-S bond {bonds[0]:.3f} A out of range")
    # interlayer S-S contact: S planes facing the vdW gap at z ~ 0.5
    # (0.379-plane of layer 1 vs 0.621-plane of layer 2), NOT the
    # same-column intra-sandwich pair.
    lo = [i for i in ss if 0.30 < frac[i][2] % 1.0 < 0.50]
    hi = [i for i in ss if 0.50 < frac[i][2] % 1.0 < 0.70]
    inter = min(dmin(i, j) for i in lo for j in hi)
    print(f"[relax] interlayer S-S contact: {inter:.3f} A", flush=True)
    if not (3.0 < inter < 4.0):
        raise RuntimeError(f"interlayer S-S {inter:.3f} A out of range "
                           "(D3 missing or collapse?)")


def write_gen_config(cell, cfg_hiphive: Path, cfg_gen: Path) -> None:
    """Rewrite the hiphive config's structure with the relaxed cell."""
    import yaml

    with open(cfg_hiphive) as f:
        cfg = yaml.safe_load(f)
    cfg["structure"] = {
        "source": "inline",
        "symbols": [str(s) for s in cell.symbols],
        "lattice": [[float(x) for x in row] for row in np.asarray(cell.cell)],
        "scaled_positions": [[float(x) for x in row]
                             for row in cell.scaled_positions],
    }
    with open(cfg_gen, "w") as f:
        f.write(f"## GENERATED by _run_mos2_fc.py -- relaxed structure "
                f"injected into {cfg_hiphive.name}. Do not edit.\n")
        yaml.safe_dump(cfg, f, sort_keys=False)
    print(f"[gen  ] wrote {cfg_gen}", flush=True)


def main(argv=None) -> int:
    import argparse

    from phonon_inputs.config import load_config
    from phonon_inputs.structure import load_structure
    from phonon_inputs.qe_interface import run_vasp_relax

    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--variant", default="d3", choices=sorted(VARIANTS),
                    help="exchange-correlation variant (default: d3, the "
                         "original PBE+D3 campaign)")
    ap.add_argument("--relax-only", action="store_true",
                    help="stop after the relax stage and the gen config; "
                         "use to inspect the geometry before 40 statics")
    args = ap.parse_args(argv)

    relax_name, hiphive_name, gen_name = VARIANTS[args.variant]
    cfg_relax = CFG_DIR / relax_name
    cfg_hiphive = CFG_DIR / hiphive_name
    cfg_gen = CFG_DIR / gen_name
    print(f"[stage] variant {args.variant}: {relax_name} -> {gen_name}",
          flush=True)

    config = load_config(cfg_relax)
    base_dir = cfg_relax.parent
    cell = load_structure(config.structure)

    rc = config.relax
    relaxed = run_vasp_relax(
        cell, base_dir / rc.work_dir, config.vasp,
        calculation=rc.calculation,
        forc_conv_thr=rc.forc_conv_thr,
        timeout=86400,
    )
    validate_relaxed(relaxed, cell)
    write_gen_config(relaxed, cfg_hiphive, cfg_gen)

    if args.relax_only:
        print("[done ] --relax-only: stopping before the statics.", flush=True)
        return 0

    print("[stage] fc3-hiphive-all (sow -> run -> reap)", flush=True)
    rcode = subprocess.call(
        [sys.executable, "-m", "phonon_inputs", "fc3-hiphive-all",
         "--config", str(cfg_gen)],
        cwd=str(REPO / "phonon"),
    )
    if rcode != 0:
        raise RuntimeError(f"fc3-hiphive-all failed (exit {rcode})")
    print("[done ] MoS2 FC campaign complete.", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
