simulation_dir = "/home/paul/Documents/ETH/master/quatrex/phonon/studies/out/anderson_test/local_L2"
input_dir = "/home/paul/Documents/ETH/master/quatrex/phonon/studies/out/anderson_test/local_L2"
output_dir = "/home/paul/Documents/ETH/master/quatrex/phonon/studies/out/anderson_test/local_L2/out"
formalism = "negf"
simulation_type = "phonon"

[device]
transport_direction = "z"
construct_from_unit_cell = true
num_transport_cells = 2
neighbor_cell_cutoff = [0, 0, 1]
kpoint_grid = [1, 1, 1]
kpoint_shift = [0, 0, 0]
[device.num_orbitals_per_atom]
C = 3

[scba]
max_iterations = 250
min_iterations = 3
mixing_factor = 0.2
mixing_method = "linear"

phonon = true

[electron]
energy_window_min = 0.0
energy_window_max = 55.0
energy_window_num = 181

[phonon]
eta = 1e-12
eta_obc = 0.0
left_temperature = 305.0
right_temperature = 295.0
model = "negf"
fc3_path = "/home/paul/Documents/ETH/master/quatrex/phonon/studies/out/anderson_test/local_L2/fc3_blocks.hdf5"
retarded_method = "fft"
sigma_convergence_tol = 1e-3
heat_flow_conservation_tol = 1e-2

[phonon.solver]
compute_current = true
max_batch_size = 100000
algorithm = "rgf"
[phonon.obc]
algorithm = "spectral"
nevp_solver = "full"
block_sections = 1

[outputs]
save_profiling_results = false

[compute]
numba_num_threads = 1
blas_num_threads = 1

[compute.comm]
block_comm_size = 1
q_comm_size = 1
